### ISSUE TITLE
GDB is built without python support

### ISSUE THREAD

**Issue by spaun2002** [StephanTLavavej/mingw-distro#1]
As GDB is built without python support, it's impossible to use it with QtCreator or CLion as a debugger (and it's impossible to use embedded QtCreator GDB to debug binaries built with this version of gcc)

**Comment by StephanTLavavej** [comment]
I have no interest in GDB, and added it purely to stop people complaining. Previously, I would have rejected this because I won't install Python (I hate installers). However, it looks like MSYS2 *might* have a no-installer version of Python. I would be *willing* to consider a pull request, with the following:

* Confirming that Python can be obtained via MSYS2 without system-wide modification.
* Updating README.md with the Python package incantation.
* Updating gdb.sh accordingly.
* Possibly updating mingw-w64+gcc.sh to preserve the Python pretty printers, which I believe I am currently deleting as useless garbage.

I won't do this work myself, but if handed to me on a platter, I will consider it in the interests of getting people to stop asking about GDB.

**Comment by LB--** [comment]
I'm curious, what do you use as a debugger instead?

**Comment by StephanTLavavej** [comment]
I think really hard and avoid writing bugs. At work, where I have to deal with other people's code, I use VS (devenv).

**Comment by ismail** [comment]
This wouldn't be easy to do. Python's mingw support is just outright embarrassing. See https://bugs.python.org/issue4709 and many more related bugs.

**Comment by StephanTLavavej** [comment]
Thanks, @ismail . I'll close this as wontfix, then.
