### ISSUE TITLE
Add GLFW as a lightweight alternative to SDL

### ISSUE THREAD

**Issue by sol-prog** [StephanTLavavej/mingw-distro#14]
GLFW could be used as a lightweight alternative to SDL is one is interested only in creating an OpenGL context and 3D graphics.

**Comment by StephanTLavavej** [comment]
My policy is to build only what I use, and I use SDL2. I've looked at GLFW, and I like its minimalism (I use SDL2 only for setting up a window and an OpenGL context) - except that I also use SDL2_mixer for audio and have not found a superior solution yet.

Previously, SDL1's LGPL was obnoxious, but SDL2 permits static linking, so that concern has been resolved.

**Comment by StephanTLavavej** [comment]
I'm going to add this as an experiment in the next distro (I've successfully built it, but haven't tried to use it).
