### ISSUE TITLE
make should support mingw-w64 via MSYS2

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#8]
According to https://lists.gnu.org/archive/html/make-w32/2013-10/msg00029.html ,

Eli Zaretskii> The only way to build a MinGW Make that is officially supported is build_w32.bat.

I want to build `make` via MSYS2, so I've extracted/crafted a command line manually. It would be nice if I didn't have to maintain this.

**Comment by mingwandroid** [comment]
Hi Stephan, you should check out our PKGBUILDS:

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-make

and:

https://github.com/Alexpux/MSYS2-packages/tree/master/make

Eli hacks on mingw.org so 'official' from his perspective may mean from that project's perspective.

We are happy to maintain these packages as part of MSYS2. You are free to use them in your district.

**Comment by StephanTLavavej** [comment]
Hmm, the mingw-packages build uses build_w32.bat, but driven via invoking cmd. I can't remember if I tried that years ago, or if I encountered problems (in any event, it was when I was still using MSYS1). I think what I need is the ability to pass extra arguments, since there's a couple things I want to customize.

**Comment by mingwandroid** [comment]
To build our msys2 make, we use Autotools, and to build our mingw32-make we use the batch file. In both cases we apply a few patches. You could add a patches of your own, and if you can put forward good arguments for their complete generality we'd likely add your patches anyway, otherwise maintaining your own PKGBUILD(s) would be an option.

EIther way, I recommend you give makepkg (for building msys2 make) and makepkg-mingw (for building mingw32-make) a go on MSYS2. Pass -sLf to install necessary dependencies, write build logs and force overwriting existing packages (tarballs in the current directory).

**Comment by StephanTLavavej** [comment]
This issue is complaining that make, unlike all other components (except coreutils), doesn't support mingw via configure. That's a real problem that should be fixed, and this issue is a request for help from somebody who understands autotools (not me).

I'll look into driving the batch file (if it accepts extra arguments, that should work), which would be easier to maintain than my current direct gcc invocation, but I view that as a better band-aid.

I prefer to keep using my own scripts, since I understand them (my knowledge of bash is amateur at best) and they don't rely on a whole bunch of infrastructure.

**Comment by mingwandroid** [comment]
Fair enough. It bugged Alexey and it bugged me, but since the batch file's there, I guess we let it slide.
