### ISSUE TITLE
Older release binaries

### ISSUE THREAD

**Issue by TimmermanV** [StephanTLavavej/mingw-distro#86]
Do you by any chance still have the older releases (pre v8.0)? I managed to find some of them in the [Wayback Machine](https://web.archive.org/web/*/http://nuwen.net/files/mingw/mingw*) (v1.4 , v1.5 , v6.1 , v7.2) but it would be nice to have some of the other versions as well.

**Comment by StephanTLavavej** [comment]
Sorry - I intentionally delete older releases as I'm philosophically opposed to people using old development tools.

**Comment by TimmermanV** [comment]
To me, old releases are of historic interest and imho have their uses compiling old projects (e.g. if the code uses a feature that was removed). Thanks for the reply anyway.

**Comment by swaldhoer** [comment]
> Sorry - I intentionally delete older releases as I'm philosophically opposed to people using old development tools.

I think old release are somewhat even required: For reproducibility reasons or in safety certified environments, where it if just not possible/feasible to update. But in these cases, you typically have enough backups of your installer ;) Anyhow, I'd still appreciate if these were available.

**Comment by StephanTLavavej** [comment]
> For reproducibility reasons or in safety certified environments

My dude, you are downloading unsigned binaries from a guy on the internet. At least it's over HTTPS, and the guy is a prominent member of the C++ community, and he's been doing this for 20 years, but still.

> Anyhow, I'd still appreciate if these were available.

Sorry! This continues to be super intentional and I am fundamentally opposed to this request.

If you want to build your own distro, go ahead, I've gone to great lengths to provide all of the incantations. But you'll never get old binaries out of me.
